#!/usr/bin/env python3
"""
Pydantic schemas for structured LLM outputs.
Defines the data models for professional Meeting Minutes (MOM) generation.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class ActionItem(BaseModel):
    """A concrete, assignable task extracted from the meeting."""
    task: str = Field(description="Clear, actionable task description")
    owner: str = Field(description="Name of the person assigned, or 'TBD' if not explicitly stated")
    deadline: Optional[str] = Field(default=None, description="Deadline as YYYY-MM-DD, or null if not specified")
    priority: str = Field(default="Medium", description="High, Medium, or Low")
    timestamp: str = Field(description="Timestamp citation [HH:MM:SS] from the transcript where this was assigned")


class Decision(BaseModel):
    """A concrete decision or agreement reached during the meeting."""
    decision: str = Field(description="What was decided or agreed upon")
    decided_by: str = Field(description="Key decision maker(s) or 'Consensus'")
    timestamp: str = Field(description="Timestamp citation [HH:MM:SS] from the transcript")


class TopicDiscussion(BaseModel):
    """A distinct topic or subject that was discussed during the meeting."""
    topic: str = Field(description="Title or heading for the discussion topic")
    summary: str = Field(description="Concise summary of the discussion")
    speakers_involved: List[str] = Field(default_factory=list, description="Names of speakers who contributed")


class MeetingMinutes(BaseModel):
    """
    Complete structured Meeting Minutes (MOM) document.
    Generated by the LLM from a diarized transcript.
    """
    meeting_title: str = Field(description="A descriptive title inferred from the meeting content")
    meeting_date: str = Field(description="Date of the meeting (YYYY-MM-DD)")
    attendees: List[str] = Field(description="List of detected participants/speakers")
    executive_summary: str = Field(description="2-4 paragraph professional executive summary of the meeting")
    topics: List[TopicDiscussion] = Field(default_factory=list, description="Key topics discussed")
    decisions: List[Decision] = Field(default_factory=list, description="Decisions made during the meeting")
    action_items: List[ActionItem] = Field(default_factory=list, description="Action items with owners and deadlines")
    open_questions: List[str] = Field(default_factory=list, description="Unresolved questions or items deferred to future meetings")
